# Profile for ARM Pinebook laptop

SYSTEM_ARCH=aarch64

INSTALL_LATEX=
INSTALL_DOCKER=1
INSTALL_QEMU=
INSTALL_VM_TOOLS=
INSTALL_GAMING=

EXCLUDE_PACKAGES=(linux-headers)
ADD_PLATFORM_PACKAGES=(linux-manjaro-headers)

