# Profile for ARM Pinebook laptop

SYSTEM_ARCH=aarch64
INSTALL_KERNEL_VARIANT=linux-aarch64

USE_LOGIN_MANAGER=greetd

INSTALL_LATEX=
INSTALL_DOCKER=1
INSTALL_QEMU=
INSTALL_VM_TOOLS=
INSTALL_GAMING=

EXCLUDE_PACKAGES=(ttf-ms-win11-auto)
ADD_PLATFORM_PACKAGES=()

