# Profile definition for desktop

SYSTEM_ARCH=amd64

INSTALL_KERNEL_VARIANT=linux-cachyos
INSTALL_MICROCODE=amd

INITCPIO_ENABLE_DROPBEAR=1

USE_LOGIN_MANAGER=greetd
INSTALL_NVIDIA_GRAPHICS=
INSTALL_AMD_GRAPHICS=

INSTALL_LATEX=
INSTALL_DOCKER=1
INSTALL_QEMU=1
INSTALL_VM_TOOLS=1
INSTALL_GAMING=1

EXCLUDE_PACKAGES=()

