#!/bin/sh

# Init environment
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
[[ -f "$XDG_CONFIG_HOME/profile.sh" ]] && . "$XDG_CONFIG_HOME/profile.sh"

# Fix DPI for toolkits (deprecated)
#export QT_AUTO_SCREEN_SCALE_FACTOR=1
#export GDK_DPI_SCALE=1.0
#export GDK_SCALE=1
