# Profile definition for laptop

SYSTEM_ARCH=amd64

INSTALL_DRIVERS=1
INSTALL_NVIDIA_GRAPHICS=1
INSTALL_INTEL_GRAPHICS=1
INSTALL_HYBRID_GRAPHICS=1

INSTALL_LATEX=1
INSTALL_DOCKER=1
INSTALL_QEMU=1
INSTALL_VM_TOOLS=1
INSTALL_GAMING=1

EXCLUDE_PACKAGES=()

