#!/bin/bash
# From https://github.com/iTrooz/initcpio-hook-shadowcopy

build() {
  if [[ -f /etc/shadow.initramfs ]]; then
    msg "shadowcopy: Using /etc/shadow.initramfs"
    add_file /etc/shadow.initramfs /etc/shadow
  fi
}

help() {
    echo "Copies /etc/shadow.initramfs into initramfs /etc/shadow"
}
