Vagrant.configure("2") do |config|
  
  config.vm.provider :libvirt do |libvirt|
    libvirt.storage_pool_name = 'vagrant'
  end

  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = :host
  end
end


